### PR TITLE
Add: Calculator-JS

### PR DESCRIPTION
**Pull request by icoderharshit**
Hey @vijaygupta18 , you are doing a wonderful job by maintaining such a nice repository. I just added my own project which is basically a calculator made using HTML, CSS & jQuery. This is my first PR for Hacktoberfest '21, I hope you'll merge this into the main branch and give the required hacktoberfest labels.
Thank you :)

### CODE REVIEW

**Comment by vijaygupta18** [comment]
Do give a Star to this repo.. happy hacking.

**Comment by icoderharshit** [comment]
@vijaygupta18 Please add the required PR accepted labels on this PR for Hacktoberfest '21, because it is still showing PR not accepted yet.

**Comment by icoderharshit** [comment]
@vijaygupta18 Yes, I just did. This is really a nice repository and why not if it has such an active maintainer like you. Thanks man. I'm contributing more to this repository, hope you'll merge my future PR's too :)

**Comment by vijaygupta18** [comment]
> @vijaygupta18 Yes, I just did. This is really a nice repository and why not if it has such an active maintainer like you. Thanks man. I'm contributing more to this repository, hope you'll merge my future PR's too :)

sure.

**Pull request merged**
