### PR TITLE
Created some C programs

### PR DESCRIPTION
**Pull request by Mr-vabs**
This contain linked list and sorting algorithms along with one matrix operation.

### CODE REVIEW

**Comment by Mr-vabs** [comment]
Please accept it

**Comment by vijaygupta18** [comment]
Congratulations for your Open source contribution. Don't forget to add a star on this repo.. Happy hacking

**Comment by Mr-vabs** [comment]
Already starred it, thanks for your time

**Comment by Mr-vabs** [comment]
@vijaygupta18 sir please label it hacktoberfest-accepted

**Comment by vijaygupta18** [comment]
> @vijaygupta18 sir please label it hacktoberfest-accepted

repo is already labelled as Hactoberfest accepted don't worry about it.

**Pull request merged**
