### PR TITLE
Added linearsearch.cpp

### PR DESCRIPTION
**Pull request by ankur12-1610**
Added linearsearch algorithm in cpp

### CODE REVIEW

**Comment by vijaygupta18** [comment]
star this repo.

**Comment by ankur12-1610** [comment]
> star this repo.

okay

**Comment by vijaygupta18** [comment]
Do give a star to this repo

**Comment by ankur12-1610** [comment]
@vijaygupta18 is there any requirement of the label like `hacktoberfest-accepted` etc?

**Comment by vijaygupta18** [comment]
> @vijaygupta18 is there any requirement of the label like `hacktoberfest-accepted` etc?

No if you pr is valid then it will count towards your contribution.

**Pull request merged**
