### PR TITLE
Added a Prediction using kmeans

### PR DESCRIPTION
**Pull request by AdityaSawant21**
## Added a Folder in which a Prediction using k-means Clustering Algorithms is shown
- This Folder includes a dataset and a .ipynb file
- The Dataset is included for ease of Developer contributing further.
- kmeans.ipynb file is well explained by me to understand various steps of Prediction.

### CODE REVIEW

**Comment by AdityaSawant21** [comment]
Please Review my PR and merge it

**Comment by vijaygupta18** [comment]
``congratulations on your hactoberfest contribution. if you like this repo then give it a star. Happy hacking..

**Comment by AdityaSawant21** [comment]
Can you please label this PR as hacktoberfest-accepted?

**Comment by AdityaSawant21** [comment]
> ``congratulations on your hactoberfest contribution. if you like this repo then give it a star. Happy hacking..

Sure ✌

**Pull request merged**
